name: weather
description: "A weather forecast app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  provider: ^6.0.5
  intl: ^0.20.2
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  lottie: ^3.3.1
  flutter_animate: ^4.3.0
  google_mobile_ads: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  home_widget: ^0.8.0
  workmanager: ^0.9.0+2
  visibility_detector: ^0.4.0+2
  # 地图相关
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  # 分享相关
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  # 图片选择
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# 应用图标配置
flutter_icons:
  android: "ic_launcher"
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"